# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    project:
      default:
        threshold: 1%
# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "examples"
  - "benches"
# https://docs.codecov.com/docs/pull-request-comments
comment:
  require_changes: true
