# https://embarkstudios.github.io/cargo-deny/checks/cfg.html

[graph]
targets = [
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "aarch64-apple-darwin" },
  { triple = "x86_64-pc-windows-msvc" },
]

[licenses]
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC"]
exceptions = [{ allow = ["Unicode-3.0"], crate = "unicode-ident" }]
