[package]
name = "opencc-sys"
version = "0.1.0+1.1.5"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Terakomari <im.terakomari@icloud.com>"]
repository = "https://github.com/novel-rs/opencc-rs"
homepage = "https://github.com/novel-rs/opencc-rs"
documentation = ""
description = "OpenCC bindings for Rust"
keywords = ["opencc", "chinese", "traditional", "simple"]
categories = ["external-ffi-bindings"]
links = "opencc"
build = "build.rs"

[dependencies]
# https://github.com/rust-lang-nursery/lazy-static.rs
lazy_static = "1.4.0"

[build-dependencies]
# https://github.com/rust-lang/cmake-rs
cmake = "0.1.49"
# https://github.com/rust-lang/rust-bindgen
bindgen = "0.63.0"
