name: Clippy

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/Swatinem/rust-cache
      - name: Cache
        uses: Swatinem/rust-cache@v2

      # https://github.com/dtolnay/rust-toolchain
      - name: Install Clippy
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Run Clippy
        run: cargo clippy --workspace --locked --all-targets -- --deny clippy::all
