name: Publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

env:
  PYTHONDONTWRITEBYTECODE: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # https://github.com/Swatinem/rust-cache
      - name: Cache
        uses: Swatinem/rust-cache@v2

      # https://github.com/dtolnay/rust-toolchain
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      # https://github.com/obi1kenobi/cargo-semver-checks-action
      - name: Check semver
        if: ${{ startsWith(github.ref_name, 'opencc-sys') }}
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          package: opencc-sys

      - name: Publish opencc-sys
        if: ${{ startsWith(github.ref_name, 'opencc-sys') }}
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        working-directory: opencc-sys

      # https://github.com/obi1kenobi/cargo-semver-checks-action
      - name: Check semver
        if: ${{ startsWith(github.ref_name, 'opencc-rs') }}
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          package: opencc-rs

      - name: Publish opencc-rs
        if: ${{ startsWith(github.ref_name, 'opencc-rs') }}
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
