name: Publish

on:
  release:
    # # https://stackoverflow.com/questions/59319281/github-action-different-between-release-created-and-published
    types: [published]

permissions:
  contents: read

env:
  PYTHONDONTWRITEBYTECODE: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # https://github.com/Swatinem/rust-cache
      - name: Cache
        uses: Swatinem/rust-cache@v2

      # https://github.com/dtolnay/rust-toolchain
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      # https://github.com/katyo/publish-crates
      - name: Upload release to crates.io
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
