name: Udeps

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  udeps:
    name: Udeps
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/Swatinem/rust-cache
      - name: Cache
        uses: Swatinem/rust-cache@v2

      # https://github.com/dtolnay/rust-toolchain
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      # https://github.com/taiki-e/install-action
      - name: Install cargo-udeps
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-udeps

      # https://github.com/est31/cargo-udeps
      - name: Run cargo-udeps
        run: cargo +nightly udeps --workspace --locked --all-targets
